export const ORDER_CREATION_SUBSCRIPTION_MESSAGE_TYPE = 'OrderCreated';

export const ORDER_SUBSCRIPTION_MESSAGE_TYPES = [
  ORDER_CREATION_SUBSCRIPTION_MESSAGE_TYPE,
];

export const NOTIFICATION_TYPE_RESOURCE_CREATED = 'ResourceCreated';

export const CUSTOMER_CREATION_SUBSCRIPTION_MESSAGE_TYPE = 'CustomerCreated';

export const CUSTOMER_SUBSCRIPTION_MESSAGE_TYPES = [
  CUSTOMER_CREATION_SUBSCRIPTION_MESSAGE_TYPE,
];
